# Generated by Django 6.0 on 2025-12-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poimaster",
            fields=[
                (
                    "poi_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="资源点ID"
                    ),
                ),
                (
                    "poi_name",
                    models.CharField(max_length=255, verbose_name="资源点名称"),
                ),
                (
                    "poi_type",
                    models.CharField(
                        help_text="如：景区、酒店、餐厅等",
                        max_length=100,
                        verbose_name="资源点类型",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "POI 资源点",
                "verbose_name_plural": "POI 资源点",
                "db_table": "poimaster",
                "ordering": ["poi_id"],
            },
        ),
        migrations.CreateModel(
            name="Dynamicdata",
            fields=[
                (
                    "record_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="记录ID"
                    ),
                ),
                ("record_time", models.DateTimeField(verbose_name="记录时间")),
                (
                    "passenger_flow",
                    models.IntegerField(blank=True, null=True, verbose_name="客流量"),
                ),
                (
                    "occupancy_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="百分比，如 85.50 表示 85.5%",
                        max_digits=5,
                        null=True,
                        verbose_name="入住率/占用率",
                    ),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attractions.poimaster",
                        verbose_name="关联POI",
                    ),
                ),
            ],
            options={
                "verbose_name": "动态数据",
                "verbose_name_plural": "动态数据",
                "db_table": "dynamicdata",
                "ordering": ["-record_time"],
            },
        ),
        migrations.CreateModel(
            name="Scenicspotdetails",
            fields=[
                (
                    "s_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="景区详情ID"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="如：5A、4A",
                        max_length=10,
                        null=True,
                        verbose_name="景区级别",
                    ),
                ),
                (
                    "max_capacity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最大承载量"
                    ),
                ),
                (
                    "scenic_spot",
                    models.OneToOneField(
                        help_text="景区ID=poi_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attractions.poimaster",
                        verbose_name="关联POI",
                    ),
                ),
            ],
            options={
                "verbose_name": "景区详情",
                "verbose_name_plural": "景区详情",
                "db_table": "scenicspotdetails",
            },
        ),
    ]
