# Generated by Django 6.0 on 2025-12-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attractions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hoteldetails",
            fields=[
                (
                    "h_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="酒店详情ID"
                    ),
                ),
                (
                    "star_rating",
                    models.CharField(
                        blank=True,
                        help_text="如：五星级、四星级",
                        max_length=50,
                        null=True,
                        verbose_name="星级",
                    ),
                ),
                (
                    "room_count",
                    models.IntegerField(blank=True, null=True, verbose_name="房间数量"),
                ),
                (
                    "hotel",
                    models.OneToOneField(
                        help_text="酒店ID=poi_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attractions.poimaster",
                        verbose_name="关联POI",
                    ),
                ),
                (
                    "scenic_spot_detail",
                    models.ForeignKey(
                        blank=True,
                        help_text="所属景区扩展ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attractions.scenicspotdetails",
                        verbose_name="所属景区",
                    ),
                ),
            ],
            options={
                "verbose_name": "酒店详情",
                "verbose_name_plural": "酒店详情",
                "db_table": "hoteldetails",
            },
        ),
    ]
