# Generated by Django 6.0 on 2025-12-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attractions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enterpriseinfo",
            fields=[
                (
                    "enterprise_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="企业ID"
                    ),
                ),
                (
                    "enterprise_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="企业名称"
                    ),
                ),
                (
                    "enterprise_type",
                    models.CharField(
                        blank=True,
                        help_text="如：旅行社、酒店集团、景区管理公司",
                        max_length=255,
                        null=True,
                        verbose_name="企业类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业信息",
                "verbose_name_plural": "企业信息",
                "db_table": "enterpriseinfo",
                "ordering": ["enterprise_id"],
            },
        ),
        migrations.CreateModel(
            name="Enterprisepoilink",
            fields=[
                (
                    "e_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="关联ID"
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        blank=True,
                        help_text="如：拥有、管理、合作",
                        max_length=255,
                        null=True,
                        verbose_name="关系类型",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.enterpriseinfo",
                        verbose_name="企业",
                    ),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attractions.poimaster",
                        verbose_name="POI资源点",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业POI关联",
                "verbose_name_plural": "企业POI关联",
                "db_table": "enterprisepoilink",
                "unique_together": {("enterprise", "poi")},
            },
        ),
    ]
