# Generated by Django 6.0 on 2025-12-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attractions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weatheralert",
            fields=[
                (
                    "alert_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="预警ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="预警标题"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="如：红色、橙色、黄色、蓝色",
                        max_length=50,
                        null=True,
                        verbose_name="预警级别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="如：生效中、已解除",
                        max_length=50,
                        null=True,
                        verbose_name="预警状态",
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "天气预警",
                "verbose_name_plural": "天气预警",
                "db_table": "weatheralert",
                "ordering": ["-publish_time"],
            },
        ),
        migrations.CreateModel(
            name="Locationweather",
            fields=[
                (
                    "location_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="位置ID"
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="位置名称"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="温度 (℃)",
                    ),
                ),
                (
                    "conditions",
                    models.CharField(
                        blank=True,
                        help_text="如：晴、多云、雨",
                        max_length=100,
                        null=True,
                        verbose_name="天气状况",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attractions.poimaster",
                        verbose_name="关联POI",
                    ),
                ),
            ],
            options={
                "verbose_name": "位置天气",
                "verbose_name_plural": "位置天气",
                "db_table": "locationweather",
                "ordering": ["-update_time"],
            },
        ),
        migrations.CreateModel(
            name="Weatherforecast",
            fields=[
                (
                    "forecast_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="预报ID"
                    ),
                ),
                (
                    "forecast_date",
                    models.DateField(blank=True, null=True, verbose_name="预报日期"),
                ),
                (
                    "temp_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="最高温度 (℃)",
                    ),
                ),
                (
                    "temp_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="最低温度 (℃)",
                    ),
                ),
                (
                    "condition_day",
                    models.CharField(
                        blank=True,
                        help_text="如：晴、多云、雨",
                        max_length=100,
                        null=True,
                        verbose_name="白天天气",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.locationweather",
                        verbose_name="位置",
                    ),
                ),
            ],
            options={
                "verbose_name": "天气预报",
                "verbose_name_plural": "天气预报",
                "db_table": "weatherforecast",
                "ordering": ["forecast_date"],
            },
        ),
        migrations.CreateModel(
            name="Alertaffectedpoi",
            fields=[
                (
                    "a_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="关联ID"
                    ),
                ),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attractions.poimaster",
                        verbose_name="受影响POI",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.weatheralert",
                        verbose_name="天气预警",
                    ),
                ),
            ],
            options={
                "verbose_name": "预警影响POI",
                "verbose_name_plural": "预警影响POI",
                "db_table": "alertaffectedpoi",
                "unique_together": {("alert", "poi")},
            },
        ),
    ]
